# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 808)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ico/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/ico/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/ico/logo.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/ico/logo.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 481, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.files_tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.files_tableWidget.sizePolicy().hasHeightForWidth())
        self.files_tableWidget.setSizePolicy(sizePolicy)
        self.files_tableWidget.setMinimumSize(QtCore.QSize(380, 200))
        self.files_tableWidget.setAcceptDrops(True)
        self.files_tableWidget.setDragEnabled(True)
        self.files_tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.files_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.files_tableWidget.setRowCount(0)
        self.files_tableWidget.setColumnCount(2)
        self.files_tableWidget.setObjectName("files_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.files_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.files_tableWidget.setHorizontalHeaderItem(1, item)
        self.files_tableWidget.horizontalHeader().setVisible(True)
        self.files_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.files_tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.files_tableWidget.horizontalHeader().setHighlightSections(True)
        self.files_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.files_tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.files_tableWidget)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.options_tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_tableWidget.sizePolicy().hasHeightForWidth())
        self.options_tableWidget.setSizePolicy(sizePolicy)
        self.options_tableWidget.setMinimumSize(QtCore.QSize(300, 100))
        self.options_tableWidget.setAcceptDrops(True)
        self.options_tableWidget.setDragEnabled(True)
        self.options_tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.options_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.options_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.options_tableWidget.setRowCount(0)
        self.options_tableWidget.setColumnCount(2)
        self.options_tableWidget.setObjectName("options_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.options_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_tableWidget.setHorizontalHeaderItem(1, item)
        self.options_tableWidget.horizontalHeader().setVisible(True)
        self.options_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.options_tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.options_tableWidget.horizontalHeader().setHighlightSections(True)
        self.options_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.options_tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.options_tableWidget, 0, 0, 1, 1)
        self.optionButtonsLayout = QtWidgets.QHBoxLayout()
        self.optionButtonsLayout.setObjectName("optionButtonsLayout")
        self.xButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.xButton.setEnabled(False)
        self.xButton.setObjectName("xButton")
        self.optionButtonsLayout.addWidget(self.xButton)
        self.yButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.yButton.setEnabled(False)
        self.yButton.setObjectName("yButton")
        self.optionButtonsLayout.addWidget(self.yButton)
        self.cButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cButton.setEnabled(False)
        self.cButton.setObjectName("cButton")
        self.optionButtonsLayout.addWidget(self.cButton)
        self.gridLayout.addLayout(self.optionButtonsLayout, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plotter = QtWebEngineWidgets.QWebEngineView(self.groupBox_3)
        self.plotter.setMinimumSize(QtCore.QSize(600, 400))
        self.plotter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotter.setObjectName("plotter")
        self.verticalLayout_5.addWidget(self.plotter)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Settings = QtWidgets.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClassifier_Help = QtWidgets.QAction(MainWindow)
        self.actionClassifier_Help.setObjectName("actionClassifier_Help")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_Undo = QtWidgets.QAction(MainWindow)
        self.action_Undo.setObjectName("action_Undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        self.action_Redo.setObjectName("action_Redo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionCut)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionPaste)
        self.menu_Edit.addAction(self.actionDelete)
        self.menu_Help.addAction(self.actionClassifier_Help)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.action_Exit.triggered.connect(MainWindow.close)
        self.files_tableWidget.cellDoubleClicked['int', 'int'].connect(MainWindow.on_file_dblclicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Classifier"))
        self.groupBox.setTitle(_translate("MainWindow", "数据"))
        self.groupBox_2.setTitle(_translate("MainWindow", "文件列表"))
        self.files_tableWidget.setSortingEnabled(False)
        item = self.files_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename"))
        item = self.files_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据属性"))
        self.options_tableWidget.setSortingEnabled(False)
        item = self.options_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Column"))
        item = self.options_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Option"))
        self.xButton.setText(_translate("MainWindow", "设定当前项为x轴"))
        self.yButton.setText(_translate("MainWindow", "设定当前项为y轴"))
        self.cButton.setText(_translate("MainWindow", "设定当前项为类别"))
        self.groupBox_3.setTitle(_translate("MainWindow", "可视化"))
        self.menu_File.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_Edit.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menu_View.setTitle(_translate("MainWindow", "查看(&V)"))
        self.menu_Settings.setTitle(_translate("MainWindow", "设置(&S)"))
        self.menu_Help.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.actionClassifier_Help.setText(_translate("MainWindow", "分类器帮助"))
        self.actionClassifier_Help.setShortcut(_translate("MainWindow", "Ctrl+/"))
        self.action_New.setText(_translate("MainWindow", "新建(&N)"))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_Open.setText(_translate("MainWindow", "打开(&O)"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Save.setText(_translate("MainWindow", "保存(&S)"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "另存为(&A)"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_Undo.setText(_translate("MainWindow", "撤销(&U)"))
        self.action_Undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_Redo.setText(_translate("MainWindow", "重做(&R)"))
        self.action_Redo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "剪切"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "复制"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDelete.setText(_translate("MainWindow", "删除"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.action_Exit.setText(_translate("MainWindow", "退出(&X)"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Alt+X"))

from PyQt5 import QtWebEngineWidgets
import resources_rc
